# 8kcDJeNjwjxBHztdq1tx
image: "wtd-client"

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git nodejs -y )'
  # - eval $(ssh-agent -s)
  # - echo "$WTD_AWS_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  # - mkdir -p ~/.ssh
  # - chmod 700 ~/.ssh
  # - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  # - chmod 644 ~/.ssh/known_hosts
  # - git config --global user.email "shivamgoyal15@outlook.com"
  # - git config --global user.name "Shivam Goyal"


cache:
  paths:
    - node_modules/

build:
  script:
    - ls
    - npm i
    - ./node_modules/@angular/cli/bin/ng build --prod

push:
  script:
    - echo 'pushed'

